version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
      python: 3.10
    commands:
      - echo "Installing Go dependencies..."
      - cd go
      - go mod tidy
      - cd ..
  build:
    commands:
      - echo "Building Go Lambda..."
      - cd go
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o go-scraper main.go util.go player.go tournament.go tournament_list.go
      - zip go-scraper.zip go-scraper
      - cd ..
      - echo "Packaging Python Lambdas..."
      - cd python
      - zip currentMonthFIDEGlicko.zip currentMonthFIDEGlicko.py
      - zip runGlicko.zip runGlicko.py
      - cd ..
      - echo "Packaging AWS SAM template..."
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket fide-glicko-packages
artifacts:
  files:
    - go/go-scraper.zip
    - python/currentMonthFIDEGlicko.zip
    - python/runGlicko.zip
    - asl/FideScraperFlow.json
    - packaged.yaml
