AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Chess Glicko AWS Deployment
  - Go Lambda: Compiled binary packaged as go-scraper.zip
  - Python Lambdas: currentMonthFIDEGlicko.zip and runGlicko.zip
  - Step Function: FideScraperFlow.json

Globals:
  Function:
    Timeout: 30

Resources:

  GoScraperLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GoScraper
      CodeUri: go/go-scraper.zip
      Handler: go-scraper   
      Runtime: provided.al2
      Timeout: 240
      MemorySize: 3008
      Policies:
        - AWSLambdaBasicExecutionRole

  CurrentMonthLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CurrentMonthFIDEGlicko
      CodeUri: python/currentMonthFIDEGlicko.zip
      Handler: currentMonthFIDEGlicko.lambda_handler
      Runtime: python3.10
      Timeout: 3
      MemorySize: 128
      Role: arn:aws:iam::961341531973:role/LambdaS3-chess-glicko
      Policies:
        - AWSLambdaBasicExecutionRole

  RunGlickoLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RunGlicko
      CodeUri: python/runGlicko.zip
      Handler: runGlicko.lambda_handler
      Runtime: python3.10
      Timeout: 90
      MemorySize: 128
      Role: arn:aws:iam::961341531973:role/LambdaS3-chess-glicko
      Policies:
        - AWSLambdaBasicExecutionRole

  FideScraperStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: FideScraperFlow
      DefinitionUri: asl/FideScraperFlow.json
      Role: arn:aws:iam::961341531973:role/service-role/StepFunctions-FideScraperFlow-role-vqvxm5vc0
